const zoneNames = <String, List<String>>{
  'Africa/Abidjan': ['Greenwich Mean Time', 'Abidjan Daylight Time', 'Abidjan Time'],
  'Africa/Accra': ['Greenwich Mean Time', 'Accra Daylight Time', 'Accra Time'],
  'Africa/Addis_Ababa': ['East Africa Time', 'Addis Ababa Daylight Time', 'Addis Ababa Time'],
  'Africa/Algiers': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Africa/Asmara': ['East Africa Time', 'Asmara Daylight Time', 'Asmara Time'],
  'Africa/Asmera': ['East Africa Time', 'Asmara Daylight Time', 'Asmara Time'],
  'Africa/Bamako': ['Greenwich Mean Time', 'Bamako Daylight Time', 'Bamako Time'],
  'Africa/Bangui': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Banjul': ['Greenwich Mean Time', 'Banjul Daylight Time', 'Banjul Time'],
  'Africa/Bissau': ['Greenwich Mean Time', 'Bissau Daylight Time', 'Bissau Time'],
  'Africa/Blantyre': ['Central Africa Time', 'Blantyre Daylight Time', 'Blantyre Time'],
  'Africa/Brazzaville': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Bujumbura': ['Central Africa Time', 'Bujumbura Daylight Time', 'Bujumbura Time'],
  'Africa/Cairo': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Africa/Casablanca': ['Casablanca Standard Time', 'Casablanca Daylight Time', 'Casablanca Time'],
  'Africa/Ceuta': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Africa/Conakry': ['Greenwich Mean Time', 'Conakry Daylight Time', 'Conakry Time'],
  'Africa/Dakar': ['Greenwich Mean Time', 'Dakar Daylight Time', 'Dakar Time'],
  'Africa/Dar_es_Salaam': ['East Africa Time', 'Dar es Salaam Daylight Time', 'Dar es Salaam Time'],
  'Africa/Djibouti': ['East Africa Time', 'Djibouti Daylight Time', 'Djibouti Time'],
  'Africa/Douala': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/El_Aaiun': ['El Aaiun Standard Time', 'El Aaiun Daylight Time', 'El Aaiun Time'],
  'Africa/Freetown': ['Greenwich Mean Time', 'Freetown Daylight Time', 'Freetown Time'],
  'Africa/Gaborone': ['Central Africa Time', 'Gaborone Daylight Time', 'Gaborone Time'],
  'Africa/Harare': ['Central Africa Time', 'Harare Daylight Time', 'Harare Time'],
  'Africa/Johannesburg': ['South Africa Standard Time', 'Johannesburg Daylight Time', 'Johannesburg Time'],
  'Africa/Juba': ['Central Africa Time', 'Juba Daylight Time', 'Juba Time'],
  'Africa/Kampala': ['East Africa Time', 'Kampala Daylight Time', 'Kampala Time'],
  'Africa/Khartoum': ['Central Africa Time', 'Khartoum Daylight Time', 'Khartoum Time'],
  'Africa/Kigali': ['Central Africa Time', 'Kigali Daylight Time', 'Kigali Time'],
  'Africa/Kinshasa': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Lagos': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Libreville': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Lome': ['Greenwich Mean Time', 'Lome Daylight Time', 'Lome Time'],
  'Africa/Luanda': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Lubumbashi': ['Central Africa Time', 'Lubumbashi Daylight Time', 'Lubumbashi Time'],
  'Africa/Lusaka': ['Central Africa Time', 'Lusaka Daylight Time', 'Lusaka Time'],
  'Africa/Malabo': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Maputo': ['Central Africa Time', 'Maputo Daylight Time', 'Maputo Time'],
  'Africa/Maseru': ['South Africa Standard Time', 'Maseru Daylight Time', 'Maseru Time'],
  'Africa/Mbabane': ['South Africa Standard Time', 'Mbabane Daylight Time', 'Mbabane Time'],
  'Africa/Mogadishu': ['East Africa Time', 'Mogadishu Daylight Time', 'Mogadishu Time'],
  'Africa/Monrovia': ['Greenwich Mean Time', 'Monrovia Daylight Time', 'Monrovia Time'],
  'Africa/Nairobi': ['East Africa Time', 'Nairobi Daylight Time', 'Nairobi Time'],
  'Africa/Ndjamena': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Niamey': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Nouakchott': ['Greenwich Mean Time', 'Nouakchott Daylight Time', 'Nouakchott Time'],
  'Africa/Ouagadougou': ['Greenwich Mean Time', 'Ouagadougou Daylight Time', 'Ouagadougou Time'],
  'Africa/Porto-Novo': ['West Africa Standard Time', 'West Africa Summer Time', 'West Africa Time'],
  'Africa/Sao_Tome': ['Greenwich Mean Time', 'São Tomé Daylight Time', 'São Tomé Time'],
  'Africa/Timbuktu': ['Greenwich Mean Time', 'Bamako Daylight Time', 'Bamako Time'],
  'Africa/Tripoli': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Africa/Tunis': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Africa/Windhoek': ['Central Africa Time', 'Windhoek Daylight Time', 'Windhoek Time'],
  'America/Adak': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'America/Anchorage': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/Anguilla': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Antigua': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Araguaina': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Argentina/Buenos_Aires': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Catamarca': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/ComodRivadavia': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Cordoba': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Jujuy': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/La_Rioja': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Mendoza': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Rio_Gallegos': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Salta': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/San_Juan': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/San_Luis': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Tucuman': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Argentina/Ushuaia': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Aruba': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Asuncion': ['Paraguay Standard Time', 'Paraguay Summer Time', 'Paraguay Time'],
  'America/Atikokan': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Atka': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'America/Bahia': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Bahia_Banderas': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Barbados': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Belem': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Belize': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Blanc-Sablon': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Boa_Vista': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'America/Bogota': ['Colombia Standard Time', 'Colombia Summer Time', 'Colombia Time'],
  'America/Boise': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Buenos_Aires': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Cambridge_Bay': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Campo_Grande': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'America/Cancun': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Caracas': ['Venezuela Time', 'Caracas Daylight Time', 'Caracas Time'],
  'America/Catamarca': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Cayenne': ['French Guiana Time', 'Cayenne Daylight Time', 'Cayenne Time'],
  'America/Cayman': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Chicago': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Chihuahua': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Ciudad_Juarez': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Coral_Harbour': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Cordoba': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Costa_Rica': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Coyhaique': ['Coyhaique Standard Time', 'Coyhaique Daylight Time', 'Coyhaique Time'],
  'America/Creston': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Cuiaba': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'America/Curacao': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Danmarkshavn': ['Greenwich Mean Time', 'Danmarkshavn Daylight Time', 'Danmarkshavn Time'],
  'America/Dawson': ['Yukon Time', 'Dawson Daylight Time', 'Dawson Time'],
  'America/Dawson_Creek': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Denver': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Detroit': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Dominica': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Edmonton': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Eirunepe': ['Acre Standard Time', 'Acre Summer Time', 'Acre Time'],
  'America/El_Salvador': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Ensenada': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'America/Fort_Nelson': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Fort_Wayne': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Fortaleza': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Glace_Bay': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Godthab': ['Greenland Standard Time', 'Greenland Summer Time', 'Greenland Time'],
  'America/Goose_Bay': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Grand_Turk': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Grenada': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Guadeloupe': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Guatemala': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Guayaquil': ['Ecuador Time', 'Guayaquil Daylight Time', 'Guayaquil Time'],
  'America/Guyana': ['Guyana Time', 'Guyana Daylight Time', 'Guyana Time'],
  'America/Halifax': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Havana': ['Cuba Standard Time', 'Cuba Daylight Time', 'Cuba Time'],
  'America/Hermosillo': ['Mexican Pacific Standard Time', 'Mexican Pacific Daylight Time', 'Mexican Pacific Time'],
  'America/Indiana/Indianapolis': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indiana/Knox': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Indiana/Marengo': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indiana/Petersburg': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indiana/Tell_City': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Indiana/Vevay': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indiana/Vincennes': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indiana/Winamac': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Indianapolis': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Inuvik': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Iqaluit': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Jamaica': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Jujuy': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Juneau': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/Kentucky/Louisville': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Kentucky/Monticello': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Knox_IN': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Kralendijk': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/La_Paz': ['Bolivia Time', 'La Paz Daylight Time', 'La Paz Time'],
  'America/Lima': ['Peru Standard Time', 'Peru Summer Time', 'Peru Time'],
  'America/Los_Angeles': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'America/Louisville': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Lower_Princes': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Maceio': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Managua': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Manaus': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'America/Marigot': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Martinique': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Matamoros': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Mazatlan': ['Mexican Pacific Standard Time', 'Mexican Pacific Daylight Time', 'Mexican Pacific Time'],
  'America/Mendoza': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Menominee': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Merida': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Metlakatla': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/Mexico_City': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Miquelon': ['St. Pierre & Miquelon Standard Time', 'St. Pierre & Miquelon Daylight Time', 'St. Pierre & Miquelon Time'],
  'America/Moncton': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Monterrey': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Montevideo': ['Uruguay Standard Time', 'Uruguay Summer Time', 'Uruguay Time'],
  'America/Montreal': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Montserrat': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Nassau': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/New_York': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Nipigon': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Nome': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/Noronha': ['Fernando de Noronha Standard Time', 'Fernando de Noronha Summer Time', 'Fernando de Noronha Time'],
  'America/North_Dakota/Beulah': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/North_Dakota/Center': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/North_Dakota/New_Salem': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Nuuk': ['Greenland Standard Time', 'Greenland Summer Time', 'Greenland Time'],
  'America/Ojinaga': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Panama': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Pangnirtung': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Paramaribo': ['Suriname Time', 'Paramaribo Daylight Time', 'Paramaribo Time'],
  'America/Phoenix': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Port-au-Prince': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Port_of_Spain': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Porto_Acre': ['Acre Standard Time', 'Acre Summer Time', 'Acre Time'],
  'America/Porto_Velho': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'America/Puerto_Rico': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Punta_Arenas': ['Punta Arenas Standard Time', 'Punta Arenas Daylight Time', 'Punta Arenas Time'],
  'America/Rainy_River': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Rankin_Inlet': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Recife': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Regina': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Resolute': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Rio_Branco': ['Acre Standard Time', 'Acre Summer Time', 'Acre Time'],
  'America/Rosario': ['Argentina Standard Time', 'Argentina Summer Time', 'Argentina Time'],
  'America/Santa_Isabel': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'America/Santarem': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Santiago': ['Chile Standard Time', 'Chile Summer Time', 'Chile Time'],
  'America/Santo_Domingo': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Sao_Paulo': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'America/Scoresbysund': ['Greenland Standard Time', 'Greenland Summer Time', 'Greenland Time'],
  'America/Shiprock': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'America/Sitka': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/St_Barthelemy': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/St_Johns': ['Newfoundland Standard Time', 'Newfoundland Daylight Time', 'Newfoundland Time'],
  'America/St_Kitts': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/St_Lucia': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/St_Thomas': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/St_Vincent': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Swift_Current': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Tegucigalpa': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Thule': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Thunder_Bay': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Tijuana': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'America/Toronto': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'America/Tortola': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Vancouver': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'America/Virgin': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'America/Whitehorse': ['Yukon Time', 'Whitehorse Daylight Time', 'Whitehorse Time'],
  'America/Winnipeg': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'America/Yakutat': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'America/Yellowknife': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'Antarctica/Casey': ['Australian Western Standard Time', 'Australian Western Daylight Time', 'Australian Western Time'],
  'Antarctica/Davis': ['Davis Time', 'Davis Daylight Time', 'Davis Time'],
  'Antarctica/DumontDUrville': ['Dumont d’Urville Time', 'Dumont-d’Urville Daylight Time', 'Dumont-d’Urville Time'],
  'Antarctica/Macquarie': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Antarctica/Mawson': ['Mawson Time', 'Mawson Daylight Time', 'Mawson Time'],
  'Antarctica/McMurdo': ['New Zealand Standard Time', 'New Zealand Daylight Time', 'New Zealand Time'],
  'Antarctica/Palmer': ['Palmer Standard Time', 'Palmer Daylight Time', 'Palmer Time'],
  'Antarctica/Rothera': ['Rothera Time', 'Rothera Daylight Time', 'Rothera Time'],
  'Antarctica/South_Pole': ['New Zealand Standard Time', 'New Zealand Daylight Time', 'New Zealand Time'],
  'Antarctica/Syowa': ['Syowa Time', 'Syowa Daylight Time', 'Syowa Time'],
  'Antarctica/Troll': ['Greenwich Mean Time', 'Troll Daylight Time', 'Troll Time'],
  'Antarctica/Vostok': ['Vostok Time', 'Vostok Daylight Time', 'Vostok Time'],
  'Arctic/Longyearbyen': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Asia/Aden': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Almaty': ['Kazakhstan Time', 'Almaty Daylight Time', 'Almaty Time'],
  'Asia/Amman': ['Amman Standard Time', 'Amman Daylight Time', 'Amman Time'],
  'Asia/Anadyr': ['Anadyr Standard Time', 'Anadyr Summer Time', 'Anadyr Time'],
  'Asia/Aqtau': ['Kazakhstan Time', 'Aqtau Daylight Time', 'Aqtau Time'],
  'Asia/Aqtobe': ['Kazakhstan Time', 'Aqtobe Daylight Time', 'Aqtobe Time'],
  'Asia/Ashgabat': ['Turkmenistan Standard Time', 'Turkmenistan Summer Time', 'Turkmenistan Time'],
  'Asia/Ashkhabad': ['Turkmenistan Standard Time', 'Turkmenistan Summer Time', 'Turkmenistan Time'],
  'Asia/Atyrau': ['Kazakhstan Time', 'Atyrau Daylight Time', 'Atyrau Time'],
  'Asia/Baghdad': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Bahrain': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Baku': ['Azerbaijan Standard Time', 'Azerbaijan Summer Time', 'Azerbaijan Time'],
  'Asia/Bangkok': ['Indochina Time', 'Bangkok Daylight Time', 'Bangkok Time'],
  'Asia/Barnaul': ['Barnaul Standard Time', 'Barnaul Daylight Time', 'Barnaul Time'],
  'Asia/Beirut': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Asia/Bishkek': ['Kyrgyzstan Time', 'Bishkek Daylight Time', 'Bishkek Time'],
  'Asia/Brunei': ['Brunei Time', 'Brunei Daylight Time', 'Brunei Time'],
  'Asia/Calcutta': ['India Standard Time', 'Kolkata Daylight Time', 'Kolkata Time'],
  'Asia/Chita': ['Yakutsk Standard Time', 'Yakutsk Summer Time', 'Yakutsk Time'],
  'Asia/Choibalsan': ['Ulaanbaatar Standard Time', 'Ulaanbaatar Summer Time', 'Ulaanbaatar Time'],
  'Asia/Chongqing': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Chungking': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Colombo': ['India Standard Time', 'Colombo Daylight Time', 'Colombo Time'],
  'Asia/Dacca': ['Bangladesh Standard Time', 'Bangladesh Summer Time', 'Bangladesh Time'],
  'Asia/Damascus': ['Damascus Standard Time', 'Damascus Daylight Time', 'Damascus Time'],
  'Asia/Dhaka': ['Bangladesh Standard Time', 'Bangladesh Summer Time', 'Bangladesh Time'],
  'Asia/Dili': ['Timor-Leste Time', 'Dili Daylight Time', 'Dili Time'],
  'Asia/Dubai': ['Gulf Standard Time', 'Dubai Daylight Time', 'Dubai Time'],
  'Asia/Dushanbe': ['Tajikistan Time', 'Dushanbe Daylight Time', 'Dushanbe Time'],
  'Asia/Famagusta': ['Famagusta Standard Time', 'Famagusta Daylight Time', 'Famagusta Time'],
  'Asia/Gaza': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Asia/Harbin': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Hebron': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Asia/Ho_Chi_Minh': ['Indochina Time', 'Ho Chi Minh City Daylight Time', 'Ho Chi Minh City Time'],
  'Asia/Hong_Kong': ['Hong Kong Standard Time', 'Hong Kong Summer Time', 'Hong Kong Time'],
  'Asia/Hovd': ['Hovd Standard Time', 'Hovd Summer Time', 'Hovd Time'],
  'Asia/Irkutsk': ['Irkutsk Standard Time', 'Irkutsk Summer Time', 'Irkutsk Time'],
  'Asia/Istanbul': ['Istanbul Standard Time', 'Istanbul Daylight Time', 'Istanbul Time'],
  'Asia/Jakarta': ['Western Indonesia Time', 'Jakarta Daylight Time', 'Jakarta Time'],
  'Asia/Jayapura': ['Eastern Indonesia Time', 'Jayapura Daylight Time', 'Jayapura Time'],
  'Asia/Jerusalem': ['Israel Standard Time', 'Israel Daylight Time', 'Israel Time'],
  'Asia/Kabul': ['Afghanistan Time', 'Kabul Daylight Time', 'Kabul Time'],
  'Asia/Kamchatka': ['Kamchatka Standard Time', 'Kamchatka Summer Time', 'Kamchatka Time'],
  'Asia/Karachi': ['Pakistan Standard Time', 'Pakistan Summer Time', 'Pakistan Time'],
  'Asia/Kashgar': ['Urumqi Standard Time', 'Urumqi Daylight Time', 'Urumqi Time'],
  'Asia/Kathmandu': ['Nepal Time', 'Kathmandu Daylight Time', 'Kathmandu Time'],
  'Asia/Katmandu': ['Nepal Time', 'Kathmandu Daylight Time', 'Kathmandu Time'],
  'Asia/Khandyga': ['Yakutsk Standard Time', 'Yakutsk Summer Time', 'Yakutsk Time'],
  'Asia/Kolkata': ['India Standard Time', 'Kolkata Daylight Time', 'Kolkata Time'],
  'Asia/Krasnoyarsk': ['Krasnoyarsk Standard Time', 'Krasnoyarsk Summer Time', 'Krasnoyarsk Time'],
  'Asia/Kuala_Lumpur': ['Malaysia Time', 'Kuala Lumpur Daylight Time', 'Kuala Lumpur Time'],
  'Asia/Kuching': ['Brunei Time', 'Kuching Daylight Time', 'Kuching Time'],
  'Asia/Kuwait': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Macao': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Macau': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Magadan': ['Magadan Standard Time', 'Magadan Summer Time', 'Magadan Time'],
  'Asia/Makassar': ['Central Indonesia Time', 'Makassar Daylight Time', 'Makassar Time'],
  'Asia/Manila': ['Philippine Standard Time', 'Philippine Summer Time', 'Philippine Time'],
  'Asia/Muscat': ['Gulf Standard Time', 'Muscat Daylight Time', 'Muscat Time'],
  'Asia/Nicosia': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Asia/Novokuznetsk': ['Krasnoyarsk Standard Time', 'Krasnoyarsk Summer Time', 'Krasnoyarsk Time'],
  'Asia/Novosibirsk': ['Novosibirsk Standard Time', 'Novosibirsk Summer Time', 'Novosibirsk Time'],
  'Asia/Omsk': ['Omsk Standard Time', 'Omsk Summer Time', 'Omsk Time'],
  'Asia/Oral': ['Kazakhstan Time', 'Oral Daylight Time', 'Oral Time'],
  'Asia/Phnom_Penh': ['Indochina Time', 'Phnom Penh Daylight Time', 'Phnom Penh Time'],
  'Asia/Pontianak': ['Western Indonesia Time', 'Pontianak Daylight Time', 'Pontianak Time'],
  'Asia/Pyongyang': ['Korean Standard Time', 'Korean Daylight Time', 'Korean Time'],
  'Asia/Qatar': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Qostanay': ['Kazakhstan Time', 'Kostanay Daylight Time', 'Kostanay Time'],
  'Asia/Qyzylorda': ['Kazakhstan Time', 'Qyzylorda Daylight Time', 'Qyzylorda Time'],
  'Asia/Rangoon': ['Myanmar Time', 'Yangon Daylight Time', 'Yangon Time'],
  'Asia/Riyadh': ['Arabian Standard Time', 'Arabian Daylight Time', 'Arabian Time'],
  'Asia/Saigon': ['Indochina Time', 'Ho Chi Minh City Daylight Time', 'Ho Chi Minh City Time'],
  'Asia/Sakhalin': ['Sakhalin Standard Time', 'Sakhalin Summer Time', 'Sakhalin Time'],
  'Asia/Samarkand': ['Uzbekistan Standard Time', 'Uzbekistan Summer Time', 'Uzbekistan Time'],
  'Asia/Seoul': ['Korean Standard Time', 'Korean Daylight Time', 'Korean Time'],
  'Asia/Shanghai': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'Asia/Singapore': ['Singapore Standard Time', 'Singapore Daylight Time', 'Singapore Time'],
  'Asia/Srednekolymsk': ['Srednekolymsk Standard Time', 'Srednekolymsk Daylight Time', 'Srednekolymsk Time'],
  'Asia/Taipei': ['Taiwan Standard Time', 'Taiwan Daylight Time', 'Taiwan Time'],
  'Asia/Tashkent': ['Uzbekistan Standard Time', 'Uzbekistan Summer Time', 'Uzbekistan Time'],
  'Asia/Tbilisi': ['Georgia Standard Time', 'Georgia Summer Time', 'Georgia Time'],
  'Asia/Tehran': ['Iran Standard Time', 'Iran Daylight Time', 'Iran Time'],
  'Asia/Tel_Aviv': ['Israel Standard Time', 'Israel Daylight Time', 'Israel Time'],
  'Asia/Thimbu': ['Bhutan Time', 'Thimphu Daylight Time', 'Thimphu Time'],
  'Asia/Thimphu': ['Bhutan Time', 'Thimphu Daylight Time', 'Thimphu Time'],
  'Asia/Tokyo': ['Japan Standard Time', 'Japan Daylight Time', 'Japan Time'],
  'Asia/Tomsk': ['Tomsk Standard Time', 'Tomsk Daylight Time', 'Tomsk Time'],
  'Asia/Ujung_Pandang': ['Central Indonesia Time', 'Makassar Daylight Time', 'Makassar Time'],
  'Asia/Ulaanbaatar': ['Ulaanbaatar Standard Time', 'Ulaanbaatar Summer Time', 'Ulaanbaatar Time'],
  'Asia/Ulan_Bator': ['Ulaanbaatar Standard Time', 'Ulaanbaatar Summer Time', 'Ulaanbaatar Time'],
  'Asia/Urumqi': ['Urumqi Standard Time', 'Urumqi Daylight Time', 'Urumqi Time'],
  'Asia/Ust-Nera': ['Vladivostok Standard Time', 'Vladivostok Summer Time', 'Vladivostok Time'],
  'Asia/Vientiane': ['Indochina Time', 'Vientiane Daylight Time', 'Vientiane Time'],
  'Asia/Vladivostok': ['Vladivostok Standard Time', 'Vladivostok Summer Time', 'Vladivostok Time'],
  'Asia/Yakutsk': ['Yakutsk Standard Time', 'Yakutsk Summer Time', 'Yakutsk Time'],
  'Asia/Yangon': ['Cocos Islands Time', 'Yangon Daylight Time', 'Yangon Time'],
  'Asia/Yekaterinburg': ['Yekaterinburg Standard Time', 'Yekaterinburg Summer Time', 'Yekaterinburg Time'],
  'Asia/Yerevan': ['Armenia Standard Time', 'Armenia Summer Time', 'Armenia Time'],
  'Atlantic/Azores': ['Azores Standard Time', 'Azores Summer Time', 'Azores Time'],
  'Atlantic/Bermuda': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'Atlantic/Canary': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Atlantic/Cape_Verde': ['Cape Verde Standard Time', 'Cape Verde Summer Time', 'Cape Verde Time'],
  'Atlantic/Faeroe': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Atlantic/Faroe': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Atlantic/Jan_Mayen': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Atlantic/Madeira': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Atlantic/Reykjavik': ['Greenwich Mean Time', 'Reykjavik Daylight Time', 'Reykjavik Time'],
  'Atlantic/South_Georgia': ['South Georgia Time', 'South Georgia Daylight Time', 'South Georgia Time'],
  'Atlantic/St_Helena': ['Greenwich Mean Time', 'St. Helena Daylight Time', 'St. Helena Time'],
  'Atlantic/Stanley': ['Falkland Islands Standard Time', 'Falkland Islands Summer Time', 'Falkland Islands Time'],
  'Australia/ACT': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Adelaide': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Australia/Brisbane': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Broken_Hill': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Australia/Canberra': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Currie': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Darwin': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Australia/Eucla': ['Australian Central Western Standard Time', 'Australian Central Western Daylight Time', 'Australian Central Western Time'],
  'Australia/Hobart': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/LHI': ['Lord Howe Standard Time', 'Lord Howe Daylight Time', 'Lord Howe Time'],
  'Australia/Lindeman': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Lord_Howe': ['Lord Howe Standard Time', 'Lord Howe Daylight Time', 'Lord Howe Time'],
  'Australia/Melbourne': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/NSW': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/North': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Australia/Perth': ['Australian Western Standard Time', 'Australian Western Daylight Time', 'Australian Western Time'],
  'Australia/Queensland': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/South': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Australia/Sydney': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Tasmania': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/Victoria': ['Australian Eastern Standard Time', 'Australian Eastern Daylight Time', 'Australian Eastern Time'],
  'Australia/West': ['Australian Western Standard Time', 'Australian Western Daylight Time', 'Australian Western Time'],
  'Australia/Yancowinna': ['Australian Central Standard Time', 'Australian Central Daylight Time', 'Australian Central Time'],
  'Brazil/Acre': ['Acre Standard Time', 'Acre Summer Time', 'Acre Time'],
  'Brazil/DeNoronha': ['Fernando de Noronha Standard Time', 'Fernando de Noronha Summer Time', 'Fernando de Noronha Time'],
  'Brazil/East': ['Brasilia Standard Time', 'Brasilia Summer Time', 'Brasilia Time'],
  'Brazil/West': ['Amazon Standard Time', 'Amazon Summer Time', 'Amazon Time'],
  'CET': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'CST6CDT': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'Canada/Atlantic': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'Canada/Central': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'Canada/Eastern': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'Canada/Mountain': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'Canada/Newfoundland': ['Newfoundland Standard Time', 'Newfoundland Daylight Time', 'Newfoundland Time'],
  'Canada/Pacific': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'Canada/Saskatchewan': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'Canada/Yukon': ['Yukon Time', 'Whitehorse Daylight Time', 'Whitehorse Time'],
  'Chile/Continental': ['Chile Standard Time', 'Chile Summer Time', 'Chile Time'],
  'Chile/EasterIsland': ['Easter Island Standard Time', 'Easter Island Summer Time', 'Easter Island Time'],
  'Cuba': ['Cuba Standard Time', 'Cuba Daylight Time', 'Cuba Time'],
  'EET': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'EST5EDT': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'Egypt': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Eire': ['Greenwich Mean Time', 'Irish Standard Time', 'Dublin Time'],
  'Etc/GMT': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Etc/GMT+0': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Etc/GMT+1': ['GMT-01:00', 'GMT-01:00', 'GMT-01:00'],
  'Etc/GMT+10': ['GMT-10:00', 'GMT-10:00', 'GMT-10:00'],
  'Etc/GMT+11': ['GMT-11:00', 'GMT-11:00', 'GMT-11:00'],
  'Etc/GMT+12': ['GMT-12:00', 'GMT-12:00', 'GMT-12:00'],
  'Etc/GMT+2': ['GMT-02:00', 'GMT-02:00', 'GMT-02:00'],
  'Etc/GMT+3': ['GMT-03:00', 'GMT-03:00', 'GMT-03:00'],
  'Etc/GMT+4': ['GMT-04:00', 'GMT-04:00', 'GMT-04:00'],
  'Etc/GMT+5': ['GMT-05:00', 'GMT-05:00', 'GMT-05:00'],
  'Etc/GMT+6': ['GMT-06:00', 'GMT-06:00', 'GMT-06:00'],
  'Etc/GMT+7': ['GMT-07:00', 'GMT-07:00', 'GMT-07:00'],
  'Etc/GMT+8': ['GMT-08:00', 'GMT-08:00', 'GMT-08:00'],
  'Etc/GMT+9': ['GMT-09:00', 'GMT-09:00', 'GMT-09:00'],
  'Etc/GMT-0': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Etc/GMT-1': ['GMT+01:00', 'GMT+01:00', 'GMT+01:00'],
  'Etc/GMT-10': ['GMT+10:00', 'GMT+10:00', 'GMT+10:00'],
  'Etc/GMT-11': ['GMT+11:00', 'GMT+11:00', 'GMT+11:00'],
  'Etc/GMT-12': ['GMT+12:00', 'GMT+12:00', 'GMT+12:00'],
  'Etc/GMT-13': ['GMT+13:00', 'GMT+13:00', 'GMT+13:00'],
  'Etc/GMT-14': ['GMT+14:00', 'GMT+14:00', 'GMT+14:00'],
  'Etc/GMT-2': ['GMT+02:00', 'GMT+02:00', 'GMT+02:00'],
  'Etc/GMT-3': ['GMT+03:00', 'GMT+03:00', 'GMT+03:00'],
  'Etc/GMT-4': ['GMT+04:00', 'GMT+04:00', 'GMT+04:00'],
  'Etc/GMT-5': ['GMT+05:00', 'GMT+05:00', 'GMT+05:00'],
  'Etc/GMT-6': ['GMT+06:00', 'GMT+06:00', 'GMT+06:00'],
  'Etc/GMT-7': ['GMT+07:00', 'GMT+07:00', 'GMT+07:00'],
  'Etc/GMT-8': ['GMT+08:00', 'GMT+08:00', 'GMT+08:00'],
  'Etc/GMT-9': ['GMT+09:00', 'GMT+09:00', 'GMT+09:00'],
  'Etc/GMT0': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Etc/Greenwich': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Etc/UCT': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'Etc/UTC': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'Etc/Universal': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'Etc/Zulu': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'Europe/Amsterdam': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Andorra': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Astrakhan': ['Astrakhan Standard Time', 'Astrakhan Daylight Time', 'Astrakhan Time'],
  'Europe/Athens': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Belfast': ['Greenwich Mean Time', 'British Summer Time', 'London Time'],
  'Europe/Belgrade': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Berlin': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Bratislava': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Brussels': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Bucharest': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Budapest': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Busingen': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Chisinau': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Copenhagen': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Dublin': ['Greenwich Mean Time', 'Irish Standard Time', 'Dublin Time'],
  'Europe/Gibraltar': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Guernsey': ['Greenwich Mean Time', 'British Summer Time', 'Guernsey Time'],
  'Europe/Helsinki': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Isle_of_Man': ['Greenwich Mean Time', 'British Summer Time', 'Isle of Man Time'],
  'Europe/Istanbul': ['Istanbul Standard Time', 'Istanbul Daylight Time', 'Istanbul Time'],
  'Europe/Jersey': ['Greenwich Mean Time', 'British Summer Time', 'Jersey Time'],
  'Europe/Kaliningrad': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Kiev': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Kirov': ['Kirov Standard Time', 'Kirov Daylight Time', 'Kirov Time'],
  'Europe/Kyiv': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Lisbon': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Europe/Ljubljana': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/London': ['Greenwich Mean Time', 'British Summer Time', 'London Time'],
  'Europe/Luxembourg': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Madrid': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Malta': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Mariehamn': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Minsk': ['Moscow Standard Time', 'Moscow Summer Time', 'Moscow Time'],
  'Europe/Monaco': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Moscow': ['Moscow Standard Time', 'Moscow Summer Time', 'Moscow Time'],
  'Europe/Nicosia': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Oslo': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Paris': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Podgorica': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Prague': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Riga': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Rome': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Samara': ['Samara Standard Time', 'Samara Summer Time', 'Samara Time'],
  'Europe/San_Marino': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Sarajevo': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Saratov': ['Saratov Standard Time', 'Saratov Daylight Time', 'Saratov Time'],
  'Europe/Simferopol': ['Moscow Standard Time', 'Moscow Summer Time', 'Moscow Time'],
  'Europe/Skopje': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Sofia': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Stockholm': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Tallinn': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Tirane': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Tiraspol': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Ulyanovsk': ['Ulyanovsk Standard Time', 'Ulyanovsk Daylight Time', 'Ulyanovsk Time'],
  'Europe/Uzhgorod': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Vaduz': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Vatican': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Vienna': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Vilnius': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Volgograd': ['Volgograd Standard Time', 'Volgograd Summer Time', 'Volgograd Time'],
  'Europe/Warsaw': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Zagreb': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Europe/Zaporozhye': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'Europe/Zurich': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'GB': ['Greenwich Mean Time', 'British Summer Time', 'London Time'],
  'GB-Eire': ['Greenwich Mean Time', 'British Summer Time', 'London Time'],
  'GMT': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'GMT0': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Greenwich': ['Greenwich Mean Time', 'Greenwich Mean Time', 'Greenwich Mean Time'],
  'Hongkong': ['Hong Kong Standard Time', 'Hong Kong Summer Time', 'Hong Kong Time'],
  'Iceland': ['Greenwich Mean Time', 'Reykjavik Daylight Time', 'Reykjavik Time'],
  'Indian/Antananarivo': ['East Africa Time', 'Antananarivo Daylight Time', 'Antananarivo Time'],
  'Indian/Chagos': ['Indian Ocean Time', 'Chagos Daylight Time', 'Chagos Time'],
  'Indian/Christmas': ['Christmas Island Time', 'Christmas Island Daylight Time', 'Christmas Island Time'],
  'Indian/Cocos': ['Cocos Islands Time', 'Cocos Islands Daylight Time', 'Cocos Islands Time'],
  'Indian/Comoro': ['East Africa Time', 'Comoro Daylight Time', 'Comoro Time'],
  'Indian/Kerguelen': ['French Southern & Antarctic Time', 'Kerguelen Daylight Time', 'Kerguelen Time'],
  'Indian/Mahe': ['Seychelles Time', 'Mahe Daylight Time', 'Mahe Time'],
  'Indian/Maldives': ['French Southern & Antarctic Time', 'Maldives Daylight Time', 'Maldives Time'],
  'Indian/Mauritius': ['Mauritius Standard Time', 'Mauritius Summer Time', 'Mauritius Time'],
  'Indian/Mayotte': ['East Africa Time', 'Mayotte Daylight Time', 'Mayotte Time'],
  'Indian/Reunion': ['Réunion Time', 'Réunion Daylight Time', 'Réunion Time'],
  'Iran': ['Iran Standard Time', 'Iran Daylight Time', 'Iran Time'],
  'Israel': ['Israel Standard Time', 'Israel Daylight Time', 'Israel Time'],
  'Jamaica': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'Japan': ['Japan Standard Time', 'Japan Daylight Time', 'Japan Time'],
  'Kwajalein': ['Marshall Islands Time', 'Kwajalein Daylight Time', 'Kwajalein Time'],
  'Libya': ['Eastern European Standard Time', 'Eastern European Summer Time', 'Eastern European Time'],
  'MET': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'MST7MDT': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'Mexico/BajaNorte': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'Mexico/BajaSur': ['Mexican Pacific Standard Time', 'Mexican Pacific Daylight Time', 'Mexican Pacific Time'],
  'Mexico/General': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'NZ': ['New Zealand Standard Time', 'New Zealand Daylight Time', 'New Zealand Time'],
  'NZ-CHAT': ['Chatham Standard Time', 'Chatham Daylight Time', 'Chatham Time'],
  'Navajo': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'PRC': ['China Standard Time', 'China Daylight Time', 'China Time'],
  'PST8PDT': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'Pacific/Apia': ['Samoa Standard Time', 'Samoa Daylight Time', 'Samoa Time'],
  'Pacific/Auckland': ['New Zealand Standard Time', 'New Zealand Daylight Time', 'New Zealand Time'],
  'Pacific/Bougainville': ['Bougainville Standard Time', 'Bougainville Daylight Time', 'Bougainville Time'],
  'Pacific/Chatham': ['Chatham Standard Time', 'Chatham Daylight Time', 'Chatham Time'],
  'Pacific/Chuuk': ['Papua New Guinea Time', 'Chuuk Daylight Time', 'Chuuk Time'],
  'Pacific/Easter': ['Easter Island Standard Time', 'Easter Island Summer Time', 'Easter Island Time'],
  'Pacific/Efate': ['Vanuatu Standard Time', 'Vanuatu Summer Time', 'Vanuatu Time'],
  'Pacific/Enderbury': ['Phoenix Islands Time', 'Enderbury Daylight Time', 'Enderbury Time'],
  'Pacific/Fakaofo': ['Tokelau Time', 'Fakaofo Daylight Time', 'Fakaofo Time'],
  'Pacific/Fiji': ['Fiji Standard Time', 'Fiji Summer Time', 'Fiji Time'],
  'Pacific/Funafuti': ['Tuvalu Time', 'Funafuti Daylight Time', 'Funafuti Time'],
  'Pacific/Galapagos': ['Galapagos Time', 'Galapagos Daylight Time', 'Galapagos Time'],
  'Pacific/Gambier': ['Gambier Time', 'Gambier Daylight Time', 'Gambier Time'],
  'Pacific/Guadalcanal': ['Solomon Islands Time', 'Guadalcanal Daylight Time', 'Guadalcanal Time'],
  'Pacific/Guam': ['Chamorro Standard Time', 'Guam Daylight Time', 'Guam Time'],
  'Pacific/Honolulu': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'Pacific/Johnston': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'Pacific/Kanton': ['Phoenix Islands Time', 'Enderbury Daylight Time', 'Enderbury Time'],
  'Pacific/Kiritimati': ['Line Islands Time', 'Kiritimati Daylight Time', 'Kiritimati Time'],
  'Pacific/Kosrae': ['Kosrae Time', 'Kosrae Daylight Time', 'Kosrae Time'],
  'Pacific/Kwajalein': ['Marshall Islands Time', 'Kwajalein Daylight Time', 'Kwajalein Time'],
  'Pacific/Majuro': ['Marshall Islands Time', 'Majuro Daylight Time', 'Majuro Time'],
  'Pacific/Marquesas': ['Marquesas Time', 'Marquesas Daylight Time', 'Marquesas Time'],
  'Pacific/Midway': ['American Samoa Standard Time', 'American Samoa Daylight Time', 'American Samoa Time'],
  'Pacific/Nauru': ['Nauru Time', 'Nauru Daylight Time', 'Nauru Time'],
  'Pacific/Niue': ['Niue Time', 'Niue Daylight Time', 'Niue Time'],
  'Pacific/Norfolk': ['Norfolk Island Standard Time', 'Norfolk Island Daylight Time', 'Norfolk Island Time'],
  'Pacific/Noumea': ['New Caledonia Standard Time', 'New Caledonia Summer Time', 'New Caledonia Time'],
  'Pacific/Pago_Pago': ['American Samoa Standard Time', 'American Samoa Daylight Time', 'American Samoa Time'],
  'Pacific/Palau': ['Palau Time', 'Palau Daylight Time', 'Palau Time'],
  'Pacific/Pitcairn': ['Pitcairn Time', 'Pitcairn Daylight Time', 'Pitcairn Time'],
  'Pacific/Pohnpei': ['Solomon Islands Time', 'Pohnpei Daylight Time', 'Pohnpei Time'],
  'Pacific/Ponape': ['Solomon Islands Time', 'Pohnpei Daylight Time', 'Pohnpei Time'],
  'Pacific/Port_Moresby': ['Dumont d’Urville Time', 'Port Moresby Daylight Time', 'Port Moresby Time'],
  'Pacific/Rarotonga': ['Cook Islands Standard Time', 'Cook Islands Summer Time', 'Cook Islands Time'],
  'Pacific/Saipan': ['Chamorro Standard Time', 'Saipan Daylight Time', 'Saipan Time'],
  'Pacific/Samoa': ['American Samoa Standard Time', 'American Samoa Daylight Time', 'American Samoa Time'],
  'Pacific/Tahiti': ['Tahiti Time', 'Tahiti Daylight Time', 'Tahiti Time'],
  'Pacific/Tarawa': ['Marshall Islands Time', 'Tarawa Daylight Time', 'Tarawa Time'],
  'Pacific/Tongatapu': ['Tonga Standard Time', 'Tonga Summer Time', 'Tonga Time'],
  'Pacific/Truk': ['Chuuk Time', 'Chuuk Daylight Time', 'Chuuk Time'],
  'Pacific/Wake': ['Wake Island Time', 'Wake Island Daylight Time', 'Wake Island Time'],
  'Pacific/Wallis': ['Gilbert Islands Time', 'Wallis Daylight Time', 'Wallis Time'],
  'Pacific/Yap': ['Papua New Guinea Time', 'Chuuk Daylight Time', 'Chuuk Time'],
  'Poland': ['Central European Standard Time', 'Central European Summer Time', 'Central European Time'],
  'Portugal': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'ROK': ['Korean Standard Time', 'Korean Daylight Time', 'Korean Time'],
  'Singapore': ['Singapore Standard Time', 'Singapore Daylight Time', 'Singapore Time'],
  'SystemV/AST4': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'SystemV/AST4ADT': ['Atlantic Standard Time', 'Atlantic Daylight Time', 'Atlantic Time'],
  'SystemV/CST6': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'SystemV/CST6CDT': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'SystemV/EST5': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'SystemV/EST5EDT': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'SystemV/HST10': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'SystemV/MST7': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'SystemV/MST7MDT': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'SystemV/PST8': ['Pitcairn Time', 'Pitcairn Time', 'Pitcairn Time'],
  'SystemV/PST8PDT': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'SystemV/YST9': ['Gambier Time', 'Gambier Time', 'Gambier Time'],
  'SystemV/YST9YDT': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'Turkey': ['Istanbul Standard Time', 'Istanbul Daylight Time', 'Istanbul Time'],
  'UCT': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'US/Alaska': ['Alaska Standard Time', 'Alaska Daylight Time', 'Alaska Time'],
  'US/Aleutian': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'US/Arizona': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'US/Central': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'US/East-Indiana': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'US/Eastern': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'US/Hawaii': ['Hawaii-Aleutian Standard Time', 'Hawaii-Aleutian Daylight Time', 'Hawaii-Aleutian Time'],
  'US/Indiana-Starke': ['Central Standard Time', 'Central Daylight Time', 'Central Time'],
  'US/Michigan': ['Eastern Standard Time', 'Eastern Daylight Time', 'Eastern Time'],
  'US/Mountain': ['Mountain Standard Time', 'Mountain Daylight Time', 'Mountain Time'],
  'US/Pacific': ['Pacific Standard Time', 'Pacific Daylight Time', 'Pacific Time'],
  'US/Samoa': ['American Samoa Standard Time', 'American Samoa Daylight Time', 'American Samoa Time'],
  'UTC': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'Universal': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
  'W-SU': ['Moscow Standard Time', 'Moscow Summer Time', 'Moscow Time'],
  'WET': ['Western European Standard Time', 'Western European Summer Time', 'Western European Time'],
  'Zulu': ['Coordinated Universal Time', 'Coordinated Universal Time', 'Coordinated Universal Time'],
};
