name: kosher_dart
description: A Dart library for calculating Jewish zmanim (halachic times) including
  astronomical times for prayers, Shabbat, and other Jewish religious observances.

version: 2.0.20

homepage: https://github.com/yakir8/kosher_dart
#author: Yakir Benin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  lints: ^6.1.0
  vector_math: ^2.2.0

dev_dependencies:
  test: ^1.31.0
  flutter_lints: ^6.0.0
