name: kosher_dart
description: This Plugin for a specialized calendar that can calculate different
  astronomical times for Jewish zmanim or religious times for prayers and other Jewish religious duties.

version: 2.0.19

homepage: https://github.com/yakir8/kosher_dart
#author: Yakir Benin

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  lints: ^6.1.0
  vector_math: ^2.2.0

dev_dependencies:
  test: ^1.31.0
  flutter_lints: ^6.0.0
