import 'package:kosher_dart/kosher_dart.dart' as kd;

import '../kosherjava.g.dart' as kj;

typedef JavaCalendar = kj.ComprehensiveZmanimCalendar;
typedef DartCalendar = kd.ComplexZmanimCalendar;

sealed class ZmanGetter {
  const ZmanGetter(this.name);
  final String name;
}

final class InstantZman extends ZmanGetter {
  const InstantZman(super.name, this.java, this.dart);
  final kj.Instant? Function(JavaCalendar) java;
  final DateTime? Function(DartCalendar) dart;
}

final class DurationZman extends ZmanGetter {
  const DurationZman(super.name, this.java, this.dart);
  final kj.Duration? Function(JavaCalendar) java;
  final double Function(DartCalendar) dart;
}

final class RealZman extends ZmanGetter {
  const RealZman(super.name, this.java, this.dart);
  final double Function(JavaCalendar) java;
  final double Function(DartCalendar) dart;
}

final zmanGetters = <ZmanGetter>[
  InstantZman('getAlos120Minutes / getAlos120', (j) => j.alos120Minutes, (d) => d.getAlos120()),
  InstantZman('getAlos120Zmanis', (j) => j.alos120Zmanis, (d) => d.getAlos120Zmanis()),
  InstantZman('getAlos16Point1Degrees', (j) => j.alos16Point1Degrees, (d) => d.getAlos16Point1Degrees()),
  InstantZman('getAlos16Point1Degrees / getAlosHashachar', (j) => j.alos16Point1Degrees, (d) => d.getAlosHashachar()),
  InstantZman('getAlos18Degrees', (j) => j.alos18Degrees, (d) => d.getAlos18Degrees()),
  InstantZman('getAlos19Degrees', (j) => j.alos19Degrees, (d) => d.getAlos19Degrees()),
  InstantZman('getAlos19Point8Degrees', (j) => j.alos19Point8Degrees, (d) => d.getAlos19Point8Degrees()),
  InstantZman('getAlos26Degrees', (j) => j.alos26Degrees, (d) => d.getAlos26Degrees()),
  InstantZman('getAlos60Minutes / getAlos60', (j) => j.alos60Minutes, (d) => d.getAlos60()),
  InstantZman('getAlos72Minutes / getAlos72', (j) => j.alos72Minutes, (d) => d.getAlos72()),
  InstantZman('getAlos72Zmanis', (j) => j.alos72Zmanis, (d) => d.getAlos72Zmanis()),
  InstantZman('getAlos90Minutes / getAlos90', (j) => j.alos90Minutes, (d) => d.getAlos90()),
  InstantZman('getAlos90Zmanis', (j) => j.alos90Zmanis, (d) => d.getAlos90Zmanis()),
  InstantZman('getAlos96Minutes / getAlos96', (j) => j.alos96Minutes, (d) => d.getAlos96()),
  InstantZman('getAlos96Zmanis', (j) => j.alos96Zmanis, (d) => d.getAlos96Zmanis()),
  InstantZman('getAlosBaalHatanya', (j) => j.alosBaalHatanya, (d) => d.getAlosBaalHatanya()),
  RealZman('getAteretTorahSunsetOffset', (j) => j.ateretTorahSunsetOffset, (d) => d.getAteretTorahSunsetOffset()),
  InstantZman('getBainHashmashosRT13Point24Degrees / getBainHasmashosRT13Point24Degrees', (j) => j.bainHashmashosRT13Point24Degrees, (d) => d.getBainHasmashosRT13Point24Degrees()),
  InstantZman('getBainHashmashosRT13Point5MinutesBefore7Point083Degrees / getBainHasmashosRT13Point5MinutesBefore7Point083Degrees', (j) => j.bainHashmashosRT13Point5MinutesBefore7Point083Degrees, (d) => d.getBainHasmashosRT13Point5MinutesBefore7Point083Degrees()),
  InstantZman('getBainHashmashosRT2Stars / getBainHasmashosRT2Stars', (j) => j.bainHashmashosRT2Stars, (d) => d.getBainHasmashosRT2Stars()),
  InstantZman('getBainHashmashosRT58Point5Minutes / getBainHasmashosRT58Point5Minutes', (j) => j.bainHashmashosRT58Point5Minutes, (d) => d.getBainHasmashosRT58Point5Minutes()),
  InstantZman('getBainHashmashosYereim13Point5Minutes / getBainHasmashosYereim13Point5Minutes', (j) => j.bainHashmashosYereim13Point5Minutes, (d) => d.getBainHasmashosYereim13Point5Minutes()),
  InstantZman('getBainHashmashosYereim16Point875Minutes / getBainHasmashosYereim16Point875Minutes', (j) => j.bainHashmashosYereim16Point875Minutes, (d) => d.getBainHasmashosYereim16Point875Minutes()),
  InstantZman('getBainHashmashosYereim18Minutes / getBainHasmashosYereim18Minutes', (j) => j.bainHashmashosYereim18Minutes, (d) => d.getBainHasmashosYereim18Minutes()),
  InstantZman('getBainHashmashosYereim2Point1Degrees / getBainHasmashosYereim2Point1Degrees', (j) => j.bainHashmashosYereim2Point1Degrees, (d) => d.getBainHasmashosYereim2Point1Degrees()),
  InstantZman('getBainHashmashosYereim2Point8Degrees / getBainHasmashosYereim2Point8Degrees', (j) => j.bainHashmashosYereim2Point8Degrees, (d) => d.getBainHasmashosYereim2Point8Degrees()),
  InstantZman('getBainHashmashosYereim3Point05Degrees / getBainHasmashosYereim3Point5Degrees', (j) => j.bainHashmashosYereim3Point05Degrees, (d) => d.getBainHasmashosYereim3Point5Degrees()),
  InstantZman('getBeginAstronomicalTwilight', (j) => j.beginAstronomicalTwilight, (d) => d.getBeginAstronomicalTwilight()),
  InstantZman('getBeginCivilTwilight', (j) => j.beginCivilTwilight, (d) => d.getBeginCivilTwilight()),
  InstantZman('getBeginNauticalTwilight', (j) => j.beginNauticalTwilight, (d) => d.getBeginNauticalTwilight()),
  InstantZman('getCandleLighting', (j) => j.candleLighting, (d) => d.getCandleLighting()),
  RealZman('getCandleLightingOffset', (j) => j.candleLightingOffset, (d) => d.getCandleLightingOffset()),
  InstantZman('getChatzosHalayla / getSolarMidnight', (j) => j.chatzosHalayla, (d) => d.getSolarMidnight()),
  InstantZman('getChatzosHayom / getChatzos', (j) => j.chatzosHayom, (d) => d.getChatzos()),
  InstantZman('getChatzosHayomAsHalfDay / getChatzosAsHalfDay', (j) => j.chatzosHayomAsHalfDay, (d) => d.getChatzosAsHalfDay()),
  InstantZman('getEndAstronomicalTwilight', (j) => j.endAstronomicalTwilight, (d) => d.getEndAstronomicalTwilight()),
  InstantZman('getEndCivilTwilight', (j) => j.endCivilTwilight, (d) => d.getEndCivilTwilight()),
  InstantZman('getEndNauticalTwilight', (j) => j.endNauticalTwilight, (d) => d.getEndNauticalTwilight()),
  InstantZman('getFixedLocalChatzosHayom / getFixedLocalChatzos', (j) => j.fixedLocalChatzosHayom, (d) => d.getFixedLocalChatzos()),
  InstantZman('getMinchaGedola16Point1Degrees', (j) => j.minchaGedola16Point1Degrees, (d) => d.getMinchaGedola16Point1Degrees()),
  InstantZman('getMinchaGedola30Minutes', (j) => j.minchaGedola30Minutes, (d) => d.getMinchaGedola30Minutes()),
  InstantZman('getMinchaGedola72Minutes', (j) => j.minchaGedola72Minutes, (d) => d.getMinchaGedola72Minutes()),
  InstantZman('getMinchaGedolaAhavatShalom', (j) => j.minchaGedolaAhavatShalom, (d) => d.getMinchaGedolaAhavatShalom()),
  InstantZman('getMinchaGedolaAteretTorah', (j) => j.minchaGedolaAteretTorah, (d) => d.getMinchaGedolaAteretTorah()),
  InstantZman('getMinchaGedolaBaalHatanya', (j) => j.minchaGedolaBaalHatanya, (d) => d.getMinchaGedolaBaalHatanya()),
  InstantZman('getMinchaGedolaGRA / getMinchaGedola', (j) => j.minchaGedolaGRA, (d) => d.getMinchaGedola()),
  InstantZman('getMinchaGedolaGRAFixedLocalChatzos30Minutes', (j) => j.minchaGedolaGRAFixedLocalChatzos30Minutes, (d) => d.getMinchaGedolaGRAFixedLocalChatzos30Minutes()),
  InstantZman('getMinchaGedolaGRAGreaterThan30 / getMinchaGedolaGreaterThan30', (j) => j.minchaGedolaGRAGreaterThan30, (d) => d.getMinchaGedolaGreaterThan30()),
  InstantZman('getMinchaKetana16Point1Degrees', (j) => j.minchaKetana16Point1Degrees, (d) => d.getMinchaKetana16Point1Degrees()),
  InstantZman('getMinchaKetana72Minutes', (j) => j.minchaKetana72Minutes, (d) => d.getMinchaKetana72Minutes()),
  InstantZman('getMinchaKetanaAhavatShalom', (j) => j.minchaKetanaAhavatShalom, (d) => d.getMinchaKetanaAhavatShalom()),
  InstantZman('getMinchaKetanaAteretTorah', (j) => j.minchaKetanaAteretTorah, (d) => d.getMinchaKetanaAteretTorah()),
  InstantZman('getMinchaKetanaBaalHatanya', (j) => j.minchaKetanaBaalHatanya, (d) => d.getMinchaKetanaBaalHatanya()),
  InstantZman('getMinchaKetanaGRA / getMinchaKetana', (j) => j.minchaKetanaGRA, (d) => d.getMinchaKetana()),
  InstantZman('getMinchaKetanaGRAFixedLocalChatzosToSunset', (j) => j.minchaKetanaGRAFixedLocalChatzosToSunset, (d) => d.getMinchaKetanaGRAFixedLocalChatzosToSunset()),
  InstantZman('getMisheyakir10Point2Degrees', (j) => j.misheyakir10Point2Degrees, (d) => d.getMisheyakir10Point2Degrees()),
  InstantZman('getMisheyakir11Degrees', (j) => j.misheyakir11Degrees, (d) => d.getMisheyakir11Degrees()),
  InstantZman('getMisheyakir11Point5Degrees', (j) => j.misheyakir11Point5Degrees, (d) => d.getMisheyakir11Point5Degrees()),
  InstantZman('getMisheyakir12Point85Degrees', (j) => j.misheyakir12Point85Degrees, (d) => d.getMisheyakir12Point85Degrees()),
  InstantZman('getMisheyakir7Point65Degrees', (j) => j.misheyakir7Point65Degrees, (d) => d.getMisheyakir7Point65Degrees()),
  InstantZman('getMisheyakir9Point5Degrees', (j) => j.misheyakir9Point5Degrees, (d) => d.getMisheyakir9Point5Degrees()),
  InstantZman('getPlagAhavatShalom', (j) => j.plagAhavatShalom, (d) => d.getPlagAhavatShalom()),
  InstantZman('getPlagAlos16Point1DegreesToTzaisGeonim7Point083Degrees / getPlagAlos16Point1ToTzaisGeonim7Point083Degrees', (j) => j.plagAlos16Point1DegreesToTzaisGeonim7Point083Degrees, (d) => d.getPlagAlos16Point1ToTzaisGeonim7Point083Degrees()),
  InstantZman('getPlagAlosToSunset', (j) => j.plagAlosToSunset, (d) => d.getPlagAlosToSunset()),
  InstantZman('getPlagHamincha120Minutes', (j) => j.plagHamincha120Minutes, (d) => d.getPlagHamincha120Minutes()),
  InstantZman('getPlagHamincha120MinutesZmanis', (j) => j.plagHamincha120MinutesZmanis, (d) => d.getPlagHamincha120MinutesZmanis()),
  InstantZman('getPlagHamincha16Point1Degrees', (j) => j.plagHamincha16Point1Degrees, (d) => d.getPlagHamincha16Point1Degrees()),
  InstantZman('getPlagHamincha18Degrees', (j) => j.plagHamincha18Degrees, (d) => d.getPlagHamincha18Degrees()),
  InstantZman('getPlagHamincha19Point8Degrees', (j) => j.plagHamincha19Point8Degrees, (d) => d.getPlagHamincha19Point8Degrees()),
  InstantZman('getPlagHamincha26Degrees', (j) => j.plagHamincha26Degrees, (d) => d.getPlagHamincha26Degrees()),
  InstantZman('getPlagHamincha60Minutes', (j) => j.plagHamincha60Minutes, (d) => d.getPlagHamincha60Minutes()),
  InstantZman('getPlagHamincha72Minutes', (j) => j.plagHamincha72Minutes, (d) => d.getPlagHamincha72Minutes()),
  InstantZman('getPlagHamincha72MinutesZmanis', (j) => j.plagHamincha72MinutesZmanis, (d) => d.getPlagHamincha72MinutesZmanis()),
  InstantZman('getPlagHamincha90Minutes', (j) => j.plagHamincha90Minutes, (d) => d.getPlagHamincha90Minutes()),
  InstantZman('getPlagHamincha90MinutesZmanis', (j) => j.plagHamincha90MinutesZmanis, (d) => d.getPlagHamincha90MinutesZmanis()),
  InstantZman('getPlagHamincha96Minutes', (j) => j.plagHamincha96Minutes, (d) => d.getPlagHamincha96Minutes()),
  InstantZman('getPlagHamincha96MinutesZmanis', (j) => j.plagHamincha96MinutesZmanis, (d) => d.getPlagHamincha96MinutesZmanis()),
  InstantZman('getPlagHaminchaAteretTorah', (j) => j.plagHaminchaAteretTorah, (d) => d.getPlagHaminchaAteretTorah()),
  InstantZman('getPlagHaminchaBaalHatanya', (j) => j.plagHaminchaBaalHatanya, (d) => d.getPlagHaminchaBaalHatanya()),
  InstantZman('getPlagHaminchaGRA / getPlagHamincha', (j) => j.plagHaminchaGRA, (d) => d.getPlagHamincha()),
  InstantZman('getPlagHaminchaGRAFixedLocalChatzosToSunset', (j) => j.plagHaminchaGRAFixedLocalChatzosToSunset, (d) => d.getPlagHaminchaGRAFixedLocalChatzosToSunset()),
  InstantZman('getPolarSunriseBenIshChai', (j) => j.polarSunriseBenIshChai, (d) => d.getPolarSunriseBenIshChai()),
  InstantZman('getPolarSunsetBenIshChai', (j) => j.polarSunsetBenIshChai, (d) => d.getPolarSunsetBenIshChai()),
  InstantZman('getSamuchLeMinchaKetana16Point1Degrees', (j) => j.samuchLeMinchaKetana16Point1Degrees, (d) => d.getSamuchLeMinchaKetana16Point1Degrees()),
  InstantZman('getSamuchLeMinchaKetana72Minutes', (j) => j.samuchLeMinchaKetana72Minutes, (d) => d.getSamuchLeMinchaKetana72Minutes()),
  InstantZman('getSamuchLeMinchaKetanaGRA', (j) => j.samuchLeMinchaKetanaGRA, (d) => d.getSamuchLeMinchaKetanaGRA()),
  InstantZman('getSeaLevelSunrise', (j) => j.seaLevelSunrise, (d) => d.getSeaLevelSunrise()),
  InstantZman('getSeaLevelSunset', (j) => j.seaLevelSunset, (d) => d.getSeaLevelSunset()),
  DurationZman('getShaahZmanis120Minutes', (j) => j.shaahZmanis120Minutes, (d) => d.getShaahZmanis120Minutes()),
  DurationZman('getShaahZmanis120MinutesZmanis', (j) => j.shaahZmanis120MinutesZmanis, (d) => d.getShaahZmanis120MinutesZmanis()),
  DurationZman('getShaahZmanis16Point1Degrees', (j) => j.shaahZmanis16Point1Degrees, (d) => d.getShaahZmanis16Point1Degrees()),
  DurationZman('getShaahZmanis18Degrees', (j) => j.shaahZmanis18Degrees, (d) => d.getShaahZmanis18Degrees()),
  DurationZman('getShaahZmanis19Point8Degrees', (j) => j.shaahZmanis19Point8Degrees, (d) => d.getShaahZmanis19Point8Degrees()),
  DurationZman('getShaahZmanis26Degrees', (j) => j.shaahZmanis26Degrees, (d) => d.getShaahZmanis26Degrees()),
  DurationZman('getShaahZmanis60Minutes', (j) => j.shaahZmanis60Minutes, (d) => d.getShaahZmanis60Minutes()),
  DurationZman('getShaahZmanis72Minutes', (j) => j.shaahZmanis72Minutes, (d) => d.getShaahZmanis72Minutes()),
  DurationZman('getShaahZmanis72Minutes / getShaahZmanisMGA', (j) => j.shaahZmanis72Minutes, (d) => d.getShaahZmanisMGA()),
  DurationZman('getShaahZmanis72MinutesZmanis', (j) => j.shaahZmanis72MinutesZmanis, (d) => d.getShaahZmanis72MinutesZmanis()),
  DurationZman('getShaahZmanis90Minutes', (j) => j.shaahZmanis90Minutes, (d) => d.getShaahZmanis90Minutes()),
  DurationZman('getShaahZmanis90MinutesZmanis', (j) => j.shaahZmanis90MinutesZmanis, (d) => d.getShaahZmanis90MinutesZmanis()),
  DurationZman('getShaahZmanis96Minutes', (j) => j.shaahZmanis96Minutes, (d) => d.getShaahZmanis96Minutes()),
  DurationZman('getShaahZmanis96MinutesZmanis', (j) => j.shaahZmanis96MinutesZmanis, (d) => d.getShaahZmanis96MinutesZmanis()),
  DurationZman('getShaahZmanisAteretTorah', (j) => j.shaahZmanisAteretTorah, (d) => d.getShaahZmanisAteretTorah()),
  DurationZman('getShaahZmanisBaalHatanya', (j) => j.shaahZmanisBaalHatanya, (d) => d.getShaahZmanisBaalHatanya()),
  DurationZman('getShaahZmanisGRA / getShaahZmanisGra', (j) => j.shaahZmanisGRA, (d) => d.getShaahZmanisGra()),
  InstantZman('getSofZmanAchilasChametzBaalHatanya', (j) => j.sofZmanAchilasChametzBaalHatanya, (d) => d.getSofZmanAchilasChametzBaalHatanya()),
  InstantZman('getSofZmanAchilasChametzGRA', (j) => j.sofZmanAchilasChametzGRA, (d) => d.getSofZmanAchilasChametzGRA()),
  InstantZman('getSofZmanAchilasChametzMGA16Point1Degrees', (j) => j.sofZmanAchilasChametzMGA16Point1Degrees, (d) => d.getSofZmanAchilasChametzMGA16Point1Degrees()),
  InstantZman('getSofZmanAchilasChametzMGA72Minutes', (j) => j.sofZmanAchilasChametzMGA72Minutes, (d) => d.getSofZmanAchilasChametzMGA72Minutes()),
  InstantZman('getSofZmanAchilasChametzMGA72MinutesZmanis', (j) => j.sofZmanAchilasChametzMGA72MinutesZmanis, (d) => d.getSofZmanAchilasChametzMGA72MinutesZmanis()),
  InstantZman('getSofZmanBiurChametzBaalHatanya', (j) => j.sofZmanBiurChametzBaalHatanya, (d) => d.getSofZmanBiurChametzBaalHatanya()),
  InstantZman('getSofZmanBiurChametzGRA', (j) => j.sofZmanBiurChametzGRA, (d) => d.getSofZmanBiurChametzGRA()),
  InstantZman('getSofZmanBiurChametzMGA16Point1Degrees', (j) => j.sofZmanBiurChametzMGA16Point1Degrees, (d) => d.getSofZmanBiurChametzMGA16Point1Degrees()),
  InstantZman('getSofZmanBiurChametzMGA72Minutes', (j) => j.sofZmanBiurChametzMGA72Minutes, (d) => d.getSofZmanBiurChametzMGA72Minutes()),
  InstantZman('getSofZmanBiurChametzMGA72MinutesZmanis', (j) => j.sofZmanBiurChametzMGA72MinutesZmanis, (d) => d.getSofZmanBiurChametzMGA72MinutesZmanis()),
  InstantZman('getSofZmanKidushLevana15Days', (j) => j.sofZmanKidushLevana15Days, (d) => d.getSofZmanKidushLevana15Days()),
  InstantZman('getSofZmanKidushLevanaBetweenMoldos', (j) => j.sofZmanKidushLevanaBetweenMoldos, (d) => d.getSofZmanKidushLevanaBetweenMoldos()),
  InstantZman('getSofZmanShma3HoursBeforeChatzos', (j) => j.sofZmanShma3HoursBeforeChatzos, (d) => d.getSofZmanShma3HoursBeforeChatzos()),
  InstantZman('getSofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees / getSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees', (j) => j.sofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees, (d) => d.getSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees()),
  InstantZman('getSofZmanShmaAlos16Point1ToSunset', (j) => j.sofZmanShmaAlos16Point1ToSunset, (d) => d.getSofZmanShmaAlos16Point1ToSunset()),
  InstantZman('getSofZmanShmaAteretTorah', (j) => j.sofZmanShmaAteretTorah, (d) => d.getSofZmanShmaAteretTorah()),
  InstantZman('getSofZmanShmaBaalHatanya', (j) => j.sofZmanShmaBaalHatanya, (d) => d.getSofZmanShmaBaalHatanya()),
  InstantZman('getSofZmanShmaGRA', (j) => j.sofZmanShmaGRA, (d) => d.getSofZmanShmaGRA()),
  InstantZman('getSofZmanShmaGRASunriseToFixedLocalChatzos', (j) => j.sofZmanShmaGRASunriseToFixedLocalChatzos, (d) => d.getSofZmanShmaGRASunriseToFixedLocalChatzos()),
  InstantZman('getSofZmanShmaMGA120Minutes', (j) => j.sofZmanShmaMGA120Minutes, (d) => d.getSofZmanShmaMGA120Minutes()),
  InstantZman('getSofZmanShmaMGA16Point1Degrees', (j) => j.sofZmanShmaMGA16Point1Degrees, (d) => d.getSofZmanShmaMGA16Point1Degrees()),
  InstantZman('getSofZmanShmaMGA16Point1DegreesToFixedLocalChatzos', (j) => j.sofZmanShmaMGA16Point1DegreesToFixedLocalChatzos, (d) => d.getSofZmanShmaMGA16Point1DegreesToFixedLocalChatzos()),
  InstantZman('getSofZmanShmaMGA18Degrees', (j) => j.sofZmanShmaMGA18Degrees, (d) => d.getSofZmanShmaMGA18Degrees()),
  InstantZman('getSofZmanShmaMGA18DegreesToFixedLocalChatzos', (j) => j.sofZmanShmaMGA18DegreesToFixedLocalChatzos, (d) => d.getSofZmanShmaMGA18DegreesToFixedLocalChatzos()),
  InstantZman('getSofZmanShmaMGA19Point8Degrees', (j) => j.sofZmanShmaMGA19Point8Degrees, (d) => d.getSofZmanShmaMGA19Point8Degrees()),
  InstantZman('getSofZmanShmaMGA72Minutes / getSofZmanShmaMGA', (j) => j.sofZmanShmaMGA72Minutes, (d) => d.getSofZmanShmaMGA()),
  InstantZman('getSofZmanShmaMGA72Minutes', (j) => j.sofZmanShmaMGA72Minutes, (d) => d.getSofZmanShmaMGA72Minutes()),
  InstantZman('getSofZmanShmaMGA72MinutesToFixedLocalChatzos', (j) => j.sofZmanShmaMGA72MinutesToFixedLocalChatzos, (d) => d.getSofZmanShmaMGA72MinutesToFixedLocalChatzos()),
  InstantZman('getSofZmanShmaMGA72MinutesZmanis', (j) => j.sofZmanShmaMGA72MinutesZmanis, (d) => d.getSofZmanShmaMGA72MinutesZmanis()),
  InstantZman('getSofZmanShmaMGA90Minutes', (j) => j.sofZmanShmaMGA90Minutes, (d) => d.getSofZmanShmaMGA90Minutes()),
  InstantZman('getSofZmanShmaMGA90MinutesToFixedLocalChatzos', (j) => j.sofZmanShmaMGA90MinutesToFixedLocalChatzos, (d) => d.getSofZmanShmaMGA90MinutesToFixedLocalChatzos()),
  InstantZman('getSofZmanShmaMGA90MinutesZmanis', (j) => j.sofZmanShmaMGA90MinutesZmanis, (d) => d.getSofZmanShmaMGA90MinutesZmanis()),
  InstantZman('getSofZmanShmaMGA96Minutes', (j) => j.sofZmanShmaMGA96Minutes, (d) => d.getSofZmanShmaMGA96Minutes()),
  InstantZman('getSofZmanShmaMGA96MinutesZmanis', (j) => j.sofZmanShmaMGA96MinutesZmanis, (d) => d.getSofZmanShmaMGA96MinutesZmanis()),
  InstantZman('getSofZmanTfila2HoursBeforeChatzos', (j) => j.sofZmanTfila2HoursBeforeChatzos, (d) => d.getSofZmanTfila2HoursBeforeChatzos()),
  InstantZman('getSofZmanTfilaAteretTorah / getSofZmanTfilahAteretTorah', (j) => j.sofZmanTfilaAteretTorah, (d) => d.getSofZmanTfilahAteretTorah()),
  InstantZman('getSofZmanTfilaBaalHatanya', (j) => j.sofZmanTfilaBaalHatanya, (d) => d.getSofZmanTfilaBaalHatanya()),
  InstantZman('getSofZmanTfilaGRA', (j) => j.sofZmanTfilaGRA, (d) => d.getSofZmanTfilaGRA()),
  InstantZman('getSofZmanTfilaGRASunriseToFixedLocalChatzos', (j) => j.sofZmanTfilaGRASunriseToFixedLocalChatzos, (d) => d.getSofZmanTfilaGRASunriseToFixedLocalChatzos()),
  InstantZman('getSofZmanTfilaMGA120Minutes', (j) => j.sofZmanTfilaMGA120Minutes, (d) => d.getSofZmanTfilaMGA120Minutes()),
  InstantZman('getSofZmanTfilaMGA16Point1Degrees', (j) => j.sofZmanTfilaMGA16Point1Degrees, (d) => d.getSofZmanTfilaMGA16Point1Degrees()),
  InstantZman('getSofZmanTfilaMGA18Degrees', (j) => j.sofZmanTfilaMGA18Degrees, (d) => d.getSofZmanTfilaMGA18Degrees()),
  InstantZman('getSofZmanTfilaMGA19Point8Degrees', (j) => j.sofZmanTfilaMGA19Point8Degrees, (d) => d.getSofZmanTfilaMGA19Point8Degrees()),
  InstantZman('getSofZmanTfilaMGA72Minutes / getSofZmanTfilaMGA', (j) => j.sofZmanTfilaMGA72Minutes, (d) => d.getSofZmanTfilaMGA()),
  InstantZman('getSofZmanTfilaMGA72Minutes', (j) => j.sofZmanTfilaMGA72Minutes, (d) => d.getSofZmanTfilaMGA72Minutes()),
  InstantZman('getSofZmanTfilaMGA72MinutesZmanis', (j) => j.sofZmanTfilaMGA72MinutesZmanis, (d) => d.getSofZmanTfilaMGA72MinutesZmanis()),
  InstantZman('getSofZmanTfilaMGA90Minutes', (j) => j.sofZmanTfilaMGA90Minutes, (d) => d.getSofZmanTfilaMGA90Minutes()),
  InstantZman('getSofZmanTfilaMGA90MinutesZmanis', (j) => j.sofZmanTfilaMGA90MinutesZmanis, (d) => d.getSofZmanTfilaMGA90MinutesZmanis()),
  InstantZman('getSofZmanTfilaMGA96Minutes', (j) => j.sofZmanTfilaMGA96Minutes, (d) => d.getSofZmanTfilaMGA96Minutes()),
  InstantZman('getSofZmanTfilaMGA96MinutesZmanis', (j) => j.sofZmanTfilaMGA96MinutesZmanis, (d) => d.getSofZmanTfilaMGA96MinutesZmanis()),
  InstantZman('getSolarMidnight', (j) => j.solarMidnight, (d) => d.getSolarMidnight()),
  InstantZman('getSunTransit', (j) => j.sunTransit, (d) => d.getSunTransit()),
  InstantZman('getSunrise', (j) => j.sunrise, (d) => d.getSunrise()),
  InstantZman('getSunset', (j) => j.sunset, (d) => d.getSunset()),
  InstantZman('getTchilasZmanKidushLevana3Days', (j) => j.tchilasZmanKidushLevana3Days, (d) => d.getTchilasZmanKidushLevana3Days()),
  InstantZman('getTchilasZmanKidushLevana7Days', (j) => j.tchilasZmanKidushLevana7Days, (d) => d.getTchilasZmanKidushLevana7Days()),
  DurationZman('getTemporalHour', (j) => j.temporalHour, (d) => d.getTemporalHour()),
  InstantZman('getTzais120Minutes / getTzais120', (j) => j.tzais120Minutes, (d) => d.getTzais120()),
  InstantZman('getTzais120Zmanis', (j) => j.tzais120Zmanis, (d) => d.getTzais120Zmanis()),
  InstantZman('getTzais16Point1Degrees', (j) => j.tzais16Point1Degrees, (d) => d.getTzais16Point1Degrees()),
  InstantZman('getTzais18Degrees', (j) => j.tzais18Degrees, (d) => d.getTzais18Degrees()),
  InstantZman('getTzais19Point8Degrees', (j) => j.tzais19Point8Degrees, (d) => d.getTzais19Point8Degrees()),
  InstantZman('getTzais26Degrees', (j) => j.tzais26Degrees, (d) => d.getTzais26Degrees()),
  InstantZman('getTzais50Minutes / getTzais50', (j) => j.tzais50Minutes, (d) => d.getTzais50()),
  InstantZman('getTzais60Minutes / getTzais60', (j) => j.tzais60Minutes, (d) => d.getTzais60()),
  InstantZman('getTzais72Minutes / getTzais72', (j) => j.tzais72Minutes, (d) => d.getTzais72()),
  InstantZman('getTzais72Zmanis', (j) => j.tzais72Zmanis, (d) => d.getTzais72Zmanis()),
  InstantZman('getTzais90Minutes / getTzais90', (j) => j.tzais90Minutes, (d) => d.getTzais90()),
  InstantZman('getTzais90Zmanis', (j) => j.tzais90Zmanis, (d) => d.getTzais90Zmanis()),
  InstantZman('getTzais96Minutes / getTzais96', (j) => j.tzais96Minutes, (d) => d.getTzais96()),
  InstantZman('getTzais96Zmanis', (j) => j.tzais96Zmanis, (d) => d.getTzais96Zmanis()),
  InstantZman('getTzaisAteretTorah', (j) => j.tzaisAteretTorah, (d) => d.getTzaisAteretTorah()),
  InstantZman('getTzaisBaalHatanya', (j) => j.tzaisBaalHatanya, (d) => d.getTzaisBaalHatanya()),
  InstantZman('getTzaisGeonim3Point7Degrees', (j) => j.tzaisGeonim3Point7Degrees, (d) => d.getTzaisGeonim3Point7Degrees()),
  InstantZman('getTzaisGeonim3Point8Degrees', (j) => j.tzaisGeonim3Point8Degrees, (d) => d.getTzaisGeonim3Point8Degrees()),
  InstantZman('getTzaisGeonim4Point42Degrees', (j) => j.tzaisGeonim4Point42Degrees, (d) => d.getTzaisGeonim4Point42Degrees()),
  InstantZman('getTzaisGeonim4Point66Degrees', (j) => j.tzaisGeonim4Point66Degrees, (d) => d.getTzaisGeonim4Point66Degrees()),
  InstantZman('getTzaisGeonim4Point8Degrees', (j) => j.tzaisGeonim4Point8Degrees, (d) => d.getTzaisGeonim4Point8Degrees()),
  InstantZman('getTzaisGeonim5Point95Degrees', (j) => j.tzaisGeonim5Point95Degrees, (d) => d.getTzaisGeonim5Point95Degrees()),
  InstantZman('getTzaisGeonim6Point45Degrees', (j) => j.tzaisGeonim6Point45Degrees, (d) => d.getTzaisGeonim6Point45Degrees()),
  InstantZman('getTzaisGeonim7Point083Degrees', (j) => j.tzaisGeonim7Point083Degrees, (d) => d.getTzaisGeonim7Point083Degrees()),
  InstantZman('getTzaisGeonim7Point67Degrees', (j) => j.tzaisGeonim7Point67Degrees, (d) => d.getTzaisGeonim7Point67Degrees()),
  InstantZman('getTzaisGeonim8Point5Degrees / getTzais', (j) => j.tzaisGeonim8Point5Degrees, (d) => d.getTzais()),
  InstantZman('getTzaisGeonim8Point5Degrees', (j) => j.tzaisGeonim8Point5Degrees, (d) => d.getTzaisGeonim8Point5Degrees()),
  InstantZman('getTzaisGeonim9Point3Degrees', (j) => j.tzaisGeonim9Point3Degrees, (d) => d.getTzaisGeonim9Point3Degrees()),
  InstantZman('getTzaisGeonim9Point75Degrees', (j) => j.tzaisGeonim9Point75Degrees, (d) => d.getTzaisGeonim9Point75Degrees()),
  InstantZman('getZmanMolad', (j) => j.zmanMolad, (d) => d.getZmanMolad()),
];
