import { readFileSync, writeFileSync } from 'node:fs';

const rustNames = readFileSync('rust_names.txt', 'utf8').split(/\r?\n/).filter(Boolean);
const dartNames = new Set(readFileSync('dart_names.txt', 'utf8').split(/\r?\n/).filter(Boolean));
// Getters that take optional positional arguments, so the name scan misses them.
for (const name of ['getMinchaGedola', 'getMinchaKetana', 'getPlagHamincha']) dartNames.add(name);

const alias = {
  getAlos120Minutes: 'getAlos120',
  getAlos60Minutes: 'getAlos60',
  getAlos72Minutes: 'getAlos72',
  getAlos90Minutes: 'getAlos90',
  getAlos96Minutes: 'getAlos96',
  getBainHashmashosRT13Point24Degrees: 'getBainHasmashosRT13Point24Degrees',
  getBainHashmashosRT13Point5MinutesBefore7Point083Degrees:
    'getBainHasmashosRT13Point5MinutesBefore7Point083Degrees',
  getBainHashmashosRT2Stars: 'getBainHasmashosRT2Stars',
  getBainHashmashosRT58Point5Minutes: 'getBainHasmashosRT58Point5Minutes',
  getBainHashmashosYereim13Point5Minutes: 'getBainHasmashosYereim13Point5Minutes',
  getBainHashmashosYereim16Point875Minutes: 'getBainHasmashosYereim16Point875Minutes',
  getBainHashmashosYereim18Minutes: 'getBainHasmashosYereim18Minutes',
  getBainHashmashosYereim2Point1Degrees: 'getBainHasmashosYereim2Point1Degrees',
  getBainHashmashosYereim2Point8Degrees: 'getBainHasmashosYereim2Point8Degrees',
  getBainHashmashosYereim3Point05Degrees: 'getBainHasmashosYereim3Point5Degrees',
  getChatzosHayomAsHalfDay: 'getChatzosAsHalfDay',
  getChatzosHalayla: 'getSolarMidnight',
  getChatzosHayom: 'getChatzos',
  getFixedLocalChatzosHayom: 'getFixedLocalChatzos',
  getMinchaGedolaGRA: 'getMinchaGedola',
  getMinchaGedolaGRAGreaterThan30: 'getMinchaGedolaGreaterThan30',
  getMinchaKetanaGRA: 'getMinchaKetana',
  getPlagAlos16Point1DegreesToTzaisGeonim7Point083Degrees:
    'getPlagAlos16Point1ToTzaisGeonim7Point083Degrees',
  getPlagHaminchaGRA: 'getPlagHamincha',
  getSofZmanShmaAlos16Point1DegreesToTzaisGeonim7Point083Degrees:
    'getSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees',
  getSofZmanTfilaAteretTorah: 'getSofZmanTfilahAteretTorah',
  getTzais120Minutes: 'getTzais120',
  getTzais50Minutes: 'getTzais50',
  getTzais60Minutes: 'getTzais60',
  getTzais72Minutes: 'getTzais72',
  getTzais90Minutes: 'getTzais90',
  getTzais96Minutes: 'getTzais96',
};

// Rust presets with no kosher_dart counterpart at all.
const missing = {};

const mapped = [];
const unmapped = [];

for (const name of rustNames) {
  if (missing[name]) continue;
  const dartName = alias[name] ?? name;
  if (!dartNames.has(dartName)) {
    unmapped.push(`${name} -> ${dartName}`);
    continue;
  }
  mapped.push([name, dartName]);
}

if (unmapped.length) {
  console.error('UNRESOLVED:\n' + unmapped.join('\n'));
  process.exit(1);
}

const entries = mapped
  .map(([rust, dart]) => `  '${rust}': (c) => c.${dart}(),`)
  .join('\n');

const missingEntries = Object.entries(missing)
  .map(([rust, why]) => `  '${rust}': '${why}',`)
  .join('\n');

const source = `// GENERATED by tool/parity/gen_dispatch.mjs. Do not edit by hand.

import 'package:kosher_dart/kosher_dart.dart';

/// Maps a kosher-rust preset's KosherJava method name to the kosher_dart getter.
final Map<String, DateTime? Function(ComplexZmanimCalendar)> zmanDispatch = {
${entries}
};

/// kosher-rust presets kosher_dart does not implement, with the reason.
const Map<String, String> unimplementedZmanim = {
${missingEntries}
};
`;

writeFileSync(process.argv[2], source);
console.log(`mapped ${mapped.length}, unimplemented ${Object.keys(missing).length}`);
